package cn.zcw.bean;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.loginacct
     *
     * @mbggenerated
     */
    private String loginacct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.userpswd
     *
     * @mbggenerated
     */
    private String userpswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.authstatus
     *
     * @mbggenerated
     */
    private String authstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.usertype
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.cardnum
     *
     * @mbggenerated
     */
    private String cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.accttype
     *
     * @mbggenerated
     */
    private String accttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.validateCode
     *
     * @mbggenerated
     */
    private String validatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.activationstatus
     *
     * @mbggenerated
     */
    private Integer activationstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.id
     *
     * @return the value of t_member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.id
     *
     * @param id the value for t_member.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.loginacct
     *
     * @return the value of t_member.loginacct
     *
     * @mbggenerated
     */
    public String getLoginacct() {
        return loginacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.loginacct
     *
     * @param loginacct the value for t_member.loginacct
     *
     * @mbggenerated
     */
    public void setLoginacct(String loginacct) {
        this.loginacct = loginacct == null ? null : loginacct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.userpswd
     *
     * @return the value of t_member.userpswd
     *
     * @mbggenerated
     */
    public String getUserpswd() {
        return userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.userpswd
     *
     * @param userpswd the value for t_member.userpswd
     *
     * @mbggenerated
     */
    public void setUserpswd(String userpswd) {
        this.userpswd = userpswd == null ? null : userpswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.username
     *
     * @return the value of t_member.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.username
     *
     * @param username the value for t_member.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.email
     *
     * @return the value of t_member.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.email
     *
     * @param email the value for t_member.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.authstatus
     *
     * @return the value of t_member.authstatus
     *
     * @mbggenerated
     */
    public String getAuthstatus() {
        return authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.authstatus
     *
     * @param authstatus the value for t_member.authstatus
     *
     * @mbggenerated
     */
    public void setAuthstatus(String authstatus) {
        this.authstatus = authstatus == null ? null : authstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.usertype
     *
     * @return the value of t_member.usertype
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.usertype
     *
     * @param usertype the value for t_member.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.realname
     *
     * @return the value of t_member.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.realname
     *
     * @param realname the value for t_member.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.cardnum
     *
     * @return the value of t_member.cardnum
     *
     * @mbggenerated
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.cardnum
     *
     * @param cardnum the value for t_member.cardnum
     *
     * @mbggenerated
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum == null ? null : cardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.accttype
     *
     * @return the value of t_member.accttype
     *
     * @mbggenerated
     */
    public String getAccttype() {
        return accttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.accttype
     *
     * @param accttype the value for t_member.accttype
     *
     * @mbggenerated
     */
    public void setAccttype(String accttype) {
        this.accttype = accttype == null ? null : accttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.validateCode
     *
     * @return the value of t_member.validateCode
     *
     * @mbggenerated
     */
    public String getValidatecode() {
        return validatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.validateCode
     *
     * @param validatecode the value for t_member.validateCode
     *
     * @mbggenerated
     */
    public void setValidatecode(String validatecode) {
        this.validatecode = validatecode == null ? null : validatecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.createtime
     *
     * @return the value of t_member.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.createtime
     *
     * @param createtime the value for t_member.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.activationstatus
     *
     * @return the value of t_member.activationstatus
     *
     * @mbggenerated
     */
    public Integer getActivationstatus() {
        return activationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.activationstatus
     *
     * @param activationstatus the value for t_member.activationstatus
     *
     * @mbggenerated
     */
    public void setActivationstatus(Integer activationstatus) {
        this.activationstatus = activationstatus;
    }

    @Override
    public String toString() {
        return "Member{" +
                "id=" + id +
                ", loginacct='" + loginacct + '\'' +
                ", userpswd='" + userpswd + '\'' +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", authstatus='" + authstatus + '\'' +
                ", usertype='" + usertype + '\'' +
                ", realname='" + realname + '\'' +
                ", cardnum='" + cardnum + '\'' +
                ", accttype='" + accttype + '\'' +
                ", validatecode='" + validatecode + '\'' +
                ", createtime='" + createtime + '\'' +
                ", activationstatus=" + activationstatus +
                '}';
    }
}