package cn.zcw.bean;

public class Member_copy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.loginacct
     *
     * @mbggenerated
     */
    private String loginacct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.userpswd
     *
     * @mbggenerated
     */
    private String userpswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.authstatus
     *
     * @mbggenerated
     */
    private String authstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.usertype
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.cardnum
     *
     * @mbggenerated
     */
    private String cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_copy.accttype
     *
     * @mbggenerated
     */
    private String accttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.id
     *
     * @return the value of t_member_copy.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.id
     *
     * @param id the value for t_member_copy.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.loginacct
     *
     * @return the value of t_member_copy.loginacct
     *
     * @mbggenerated
     */
    public String getLoginacct() {
        return loginacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.loginacct
     *
     * @param loginacct the value for t_member_copy.loginacct
     *
     * @mbggenerated
     */
    public void setLoginacct(String loginacct) {
        this.loginacct = loginacct == null ? null : loginacct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.userpswd
     *
     * @return the value of t_member_copy.userpswd
     *
     * @mbggenerated
     */
    public String getUserpswd() {
        return userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.userpswd
     *
     * @param userpswd the value for t_member_copy.userpswd
     *
     * @mbggenerated
     */
    public void setUserpswd(String userpswd) {
        this.userpswd = userpswd == null ? null : userpswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.username
     *
     * @return the value of t_member_copy.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.username
     *
     * @param username the value for t_member_copy.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.email
     *
     * @return the value of t_member_copy.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.email
     *
     * @param email the value for t_member_copy.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.authstatus
     *
     * @return the value of t_member_copy.authstatus
     *
     * @mbggenerated
     */
    public String getAuthstatus() {
        return authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.authstatus
     *
     * @param authstatus the value for t_member_copy.authstatus
     *
     * @mbggenerated
     */
    public void setAuthstatus(String authstatus) {
        this.authstatus = authstatus == null ? null : authstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.usertype
     *
     * @return the value of t_member_copy.usertype
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.usertype
     *
     * @param usertype the value for t_member_copy.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.realname
     *
     * @return the value of t_member_copy.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.realname
     *
     * @param realname the value for t_member_copy.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.cardnum
     *
     * @return the value of t_member_copy.cardnum
     *
     * @mbggenerated
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.cardnum
     *
     * @param cardnum the value for t_member_copy.cardnum
     *
     * @mbggenerated
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum == null ? null : cardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_copy.accttype
     *
     * @return the value of t_member_copy.accttype
     *
     * @mbggenerated
     */
    public String getAccttype() {
        return accttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_copy.accttype
     *
     * @param accttype the value for t_member_copy.accttype
     *
     * @mbggenerated
     */
    public void setAccttype(String accttype) {
        this.accttype = accttype == null ? null : accttype.trim();
    }
}