package cn.zcw.bean;

public class Param {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.val
     *
     * @mbggenerated
     */
    private String val;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.id
     *
     * @return the value of t_param.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.id
     *
     * @param id the value for t_param.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.name
     *
     * @return the value of t_param.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.name
     *
     * @param name the value for t_param.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.code
     *
     * @return the value of t_param.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.code
     *
     * @param code the value for t_param.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.val
     *
     * @return the value of t_param.val
     *
     * @mbggenerated
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.val
     *
     * @param val the value for t_param.val
     *
     * @mbggenerated
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }
}