package cn.zcw.bean;

public class Project_type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    private Integer projectid;

    private Integer typeid;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProjectid() {
        return projectid;
    }

    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    public Integer getTypeid() {
        return typeid;
    }

    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    public Project_type(Integer projectid, Integer typeid) {
        this.projectid = projectid;
        this.typeid = typeid;
    }

    public Project_type() {
    }

    @Override
    public String toString() {
        return "Project_type{" +
                "id=" + id +
                ", projectid=" + projectid +
                ", typeid=" + typeid +
                '}';
    }
}