package cn.zcw.bean;

import cn.zcw.util.StringUtil;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.id
     *
     * @mbggenerated
     */
    private Integer id;

    private String name;

    private String remark;

    private Double  money;

    private Integer day;

    private String status;

    private String deploydate;

    private Long supportmoney;

    private Integer supporter;

    private Integer completion;

    private Integer memberid;

    private String createdate;

    private Integer follower;

    private String iconpath;

    private String imgpath;

    private String icon;

    private String authstatus;

    public Project() {
    }

    public Project(String name, String remark, Double money, Integer day) {
        this.name = name;
        this.remark = remark;
        this.money = money;
        this.day = day;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Double  getMoney() {
        return money;
    }

    public void setMoney(Double  money) {
        this.money = money;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public void setDeploydate(String deploydate) {
        this.deploydate = deploydate == null ? null : deploydate.trim();
    }

    public Long getSupportmoney() {
        return supportmoney;
    }

    public void setSupportmoney(Long supportmoney) {
        this.supportmoney = supportmoney;
    }

    public Integer getSupporter() {
        return supporter;
    }

    public void setSupporter(Integer supporter) {
        this.supporter = supporter;
    }

    public Integer getCompletion() {
        return completion;
    }

    public void setCompletion(Integer completion) {
        this.completion = completion;
    }

    public Integer getMemberid() {
        return memberid;
    }

    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    public Integer getFollower() {
        return follower;
    }

    public void setFollower(Integer follower) {
        this.follower = follower;
    }

    public String getIconpath() {
        return iconpath;
    }

    public void setIconpath(String iconpath) {
        this.iconpath = iconpath == null ? null : iconpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.imgpath
     *
     * @return the value of t_project.imgpath
     *
     * @mbggenerated
     */
    public String getImgpath() {
        return imgpath;
    }

    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    public String getAuthstatus() {
        return authstatus;
    }

    public String getDeploydate() {
        deploydate = StringUtil.format(new Date(), "yyyy-MM-dd");
        return deploydate;
    }
    //... ...
    public String getCreatedate() {
        createdate = StringUtil.format(new Date(), "yyyy-MM-dd");
        return createdate;
    }
    public void setAuthstatus(String authstatus) {
        this.authstatus = authstatus == null ? null : authstatus.trim();
    }

    @Override
    public String toString() {
        return "Project{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", remark='" + remark + '\'' +
                ", money=" + money +
                ", day=" + day +
                ", status='" + status + '\'' +
                ", deploydate='" + deploydate + '\'' +
                ", supportmoney=" + supportmoney +
                ", supporter=" + supporter +
                ", completion=" + completion +
                ", memberid=" + memberid +
                ", createdate='" + createdate + '\'' +
                ", follower=" + follower +
                ", iconpath='" + iconpath + '\'' +
                ", imgpath='" + imgpath + '\'' +
                ", icon='" + icon + '\'' +
                ", authstatus='" + authstatus + '\'' +
                '}';
    }
}