package cn.zcw.mapper;

import cn.zcw.bean.Accttype;
import cn.zcw.bean.AccttypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int countByExample(AccttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int deleteByExample(AccttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int insert(Accttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int insertSelective(Accttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    List<Accttype> selectByExample(AccttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    Accttype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Accttype record, @Param("example") AccttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Accttype record, @Param("example") AccttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accttype record);
}