package cn.zcw.mapper;

import cn.zcw.bean.Aictionary;
import cn.zcw.bean.AictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int countByExample(AictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int deleteByExample(AictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int insert(Aictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(Aictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    List<Aictionary> selectByExample(AictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    Aictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Aictionary record, @Param("example") AictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Aictionary record, @Param("example") AictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Aictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Aictionary record);
}