package cn.zcw.mapper;

import cn.zcw.bean.Member_copy;
import cn.zcw.bean.Member_copyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Member_copyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int countByExample(Member_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int deleteByExample(Member_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int insert(Member_copy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int insertSelective(Member_copy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    List<Member_copy> selectByExample(Member_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    Member_copy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Member_copy record, @Param("example") Member_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Member_copy record, @Param("example") Member_copyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Member_copy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member_copy record);
}