package cn.zcw.mapper;

import cn.zcw.bean.Member_project_follow;
import cn.zcw.bean.Member_project_followExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Member_project_followMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int countByExample(Member_project_followExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int deleteByExample(Member_project_followExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int insert(Member_project_follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int insertSelective(Member_project_follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    List<Member_project_follow> selectByExample(Member_project_followExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    Member_project_follow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Member_project_follow record, @Param("example") Member_project_followExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Member_project_follow record, @Param("example") Member_project_followExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Member_project_follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member_project_follow record);
}