package cn.zcw.mapper;

import cn.zcw.bean.Member_address;
import cn.zcw.bean.Member_addressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Member_addressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int countByExample(Member_addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int deleteByExample(Member_addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int insert(Member_address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int insertSelective(Member_address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    List<Member_address> selectByExample(Member_addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    Member_address selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Member_address record, @Param("example") Member_addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Member_address record, @Param("example") Member_addressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Member_address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member_address record);
}