package cn.zcw.mapper;

import cn.zcw.bean.Member_cert;
import cn.zcw.bean.Member_certExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Member_certMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int countByExample(Member_certExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int deleteByExample(Member_certExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int insert(Member_cert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int insertSelective(Member_cert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    List<Member_cert> selectByExample(Member_certExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    Member_cert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Member_cert record, @Param("example") Member_certExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Member_cert record, @Param("example") Member_certExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Member_cert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Member_cert record);
}