package cn.zcw.mapper;


import cn.zcw.bean.ParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int countByExample(ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int deleteByExample(ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int insert(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int insertSelective(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    List<Param> selectByExample(ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    Param selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Param record, @Param("example") ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Param record, @Param("example") ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Param record);
}