package cn.zcw.mapper;

import cn.zcw.bean.Project_type;
import cn.zcw.bean.Project_typeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Project_typeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int countByExample(Project_typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int deleteByExample(Project_typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int insert(Project_type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int insertSelective(Project_type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    List<Project_type> selectByExample(Project_typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    Project_type selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Project_type record, @Param("example") Project_typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Project_type record, @Param("example") Project_typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Project_type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Project_type record);
}