package cn.zcw.mapper;

import cn.zcw.bean.Project_tag;
import cn.zcw.bean.Project_tagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Project_tagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int countByExample(Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int deleteByExample(Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int insert(Project_tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int insertSelective(Project_tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    List<Project_tag> selectByExample(Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    Project_tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Project_tag record, @Param("example") Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Project_tag record, @Param("example") Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Project_tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Project_tag record);
}