package cn.zcw.mapper;

import cn.zcw.bean.Project_member;
import cn.zcw.bean.Project_memberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Project_memberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int countByExample(Project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int deleteByExample(Project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int insert(Project_member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int insertSelective(Project_member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    List<Project_member> selectByExample(Project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    Project_member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Project_member record, @Param("example") Project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Project_member record, @Param("example") Project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Project_member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Project_member record);
}