package cn.zcw.mapper;

import cn.zcw.bean.Return;
import cn.zcw.bean.ReturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int countByExample(ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int deleteByExample(ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int insert(Return record);

    int insertBatch(@Param("list")List<Return> returnList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int insertSelective(Return record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    List<Return> selectByExample(ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    Return selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Return record, @Param("example") ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Return record, @Param("example") ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Return record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Return record);
}